// Command analyze reads the JSONL trial log and writes a Markdown report:
// where the two Auto Router tracks diverge, how each setting moved the
// routing decision, and which trials and cells can and cannot support a
// conclusion.
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"log"
	"os"
	"slices"
	"strings"

	"github.com/back2debug/or-learning-roadmap/autorouter-lab/internal/assert"
)

// marker separates hand-written notes from the generated report in the output
// file. Everything above it is kept when the report is regenerated.
const marker = "<!-- Everything below this line is generated by cmd/analyze. Do not edit below it. -->"

func main() {
	log.SetFlags(0)
	var (
		logPath = flag.String("log", "logs/trials.jsonl", "JSONL trial log to read")
		genPath = flag.String("generations", "logs/generations.jsonl", "backfilled generation stats, if present")
		runs    = flag.String("run", "", "comma-separated run ids, or \"all\" (default: the most recent run)")
		outPath = flag.String("out", "", "write the report to this file, keeping any text above the generated-section marker (default: stdout)")
	)
	flag.Parse()
	if err := run(*logPath, *genPath, *runs, *outPath); err != nil {
		log.Fatalf("analyze: %v", err)
	}
}

func run(logPath, genPath, runs, outPath string) error {
	trials, skipped, err := loadTrials(logPath)
	if err != nil {
		return err
	}
	trials, runIDs, err := selectRuns(trials, runs)
	if err != nil {
		return fmt.Errorf("%w in %s", err, logPath)
	}
	gens, err := loadGenerations(genPath)
	if err != nil {
		return err
	}
	var buf bytes.Buffer
	report(&buf, runIDs, trials, gens, skipped)
	if outPath == "" {
		_, err = os.Stdout.Write(buf.Bytes())
		return err
	}
	return writeBelowMarker(outPath, buf.Bytes())
}

// writeBelowMarker replaces the generated part of a file and keeps whatever a
// person wrote above the marker.
func writeBelowMarker(path string, generated []byte) error {
	head := []byte("# Findings\n\n")
	existing, err := os.ReadFile(path) // #nosec G304 -- operator's flag
	switch {
	case err == nil:
		if i := bytes.Index(existing, []byte(marker)); i >= 0 {
			head = existing[:i]
		} else if len(bytes.TrimSpace(existing)) > 0 {
			return fmt.Errorf("%s exists but has no generated-section marker; refusing to overwrite it", path)
		}
	case !errors.Is(err, fs.ErrNotExist):
		return err
	}
	out := append(append(append([]byte{}, head...), []byte(marker+"\n\n")...), generated...)
	// The report holds model names and aggregate numbers, not prompts or
	// model output, and is meant to be committed.
	return os.WriteFile(path, out, 0o644) // #nosec G306 G703 -- the operator's own path; a tracked document
}

// loadTrials reads live trial records. The log is input like any other: a
// line that is not a trial record is counted and skipped, never trusted and
// never fatal.
func loadTrials(path string) (trials []assert.Trial, skipped int, err error) {
	f, err := os.Open(path) // #nosec G304 -- operator's flag
	if err != nil {
		return nil, 0, err
	}
	defer func() {
		if cerr := f.Close(); cerr != nil && err == nil {
			err = cerr
		}
	}()
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 64<<20)
	for sc.Scan() {
		var rec struct {
			Msg string `json:"msg"`
			assert.Trial
		}
		if json.Unmarshal(sc.Bytes(), &rec) != nil || rec.Msg != "trial" || rec.RunID == "" {
			skipped++
			continue
		}
		if rec.DryRun || rec.Status == 0 {
			continue
		}
		trials = append(trials, rec.Trial)
	}
	if err := sc.Err(); err != nil {
		return nil, 0, fmt.Errorf("read %s: %w", path, err)
	}
	return trials, skipped, nil
}

// selectRuns keeps the trials of the requested runs, in log order.
func selectRuns(trials []assert.Trial, runs string) ([]assert.Trial, []string, error) {
	var all []string
	for _, t := range trials {
		if !slices.Contains(all, t.RunID) {
			all = append(all, t.RunID)
		}
	}
	if len(all) == 0 {
		return nil, nil, errors.New("no live trials")
	}
	var want []string
	switch runs {
	case "":
		want = all[len(all)-1:] // the log is append-only, so the last is newest
	case "all":
		want = all
	default:
		for _, id := range strings.Split(runs, ",") {
			if !slices.Contains(all, id) {
				return nil, nil, fmt.Errorf("no live trials for run %q", id)
			}
			want = append(want, id)
		}
	}
	trials = slices.DeleteFunc(trials, func(t assert.Trial) bool { return !slices.Contains(want, t.RunID) })
	return trials, want, nil
}

// generation is the part of a backfilled record the report uses.
type generation struct {
	TotalCost        *float64 `json:"total_cost"`
	NativePrompt     *int     `json:"native_tokens_prompt"`
	NativeCompletion *int     `json:"native_tokens_completion"`
	NativeReasoning  *int     `json:"native_tokens_reasoning"`
}

// loadGenerations reads the backfill file if there is one. Its absence is
// normal: the report then uses the cost each response reported inline.
func loadGenerations(path string) (map[string]generation, error) {
	out := map[string]generation{}
	f, err := os.Open(path) // #nosec G304 -- operator's flag
	if errors.Is(err, fs.ErrNotExist) {
		return out, nil
	}
	if err != nil {
		return nil, err
	}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 64<<20)
	for sc.Scan() {
		var rec struct {
			Msg          string     `json:"msg"`
			GenerationID string     `json:"generation_id"`
			Status       int        `json:"status"`
			Generation   generation `json:"generation"`
		}
		if json.Unmarshal(sc.Bytes(), &rec) == nil && rec.Msg == "generation" && rec.Status == 200 && rec.GenerationID != "" {
			out[rec.GenerationID] = rec.Generation
		}
	}
	if err := errors.Join(sc.Err(), f.Close()); err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	return out, nil
}

// md makes a value safe for a Markdown table cell. Model names, task types
// and error text originate in API responses, so they are untrusted text: they
// are escaped here and never interpreted.
func md(s string) string {
	s = strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return ' '
		}
		return r
	}, s)
	return strings.NewReplacer("|", "\\|", "<", "&lt;", ">", "&gt;", "`", "'", "*", "\\*", "_", "\\_", "[", "\\[").Replace(s)
}

// row writes one Markdown table row, escaping every cell.
func row(w io.Writer, cells ...string) {
	for i, c := range cells {
		cells[i] = md(c)
	}
	fmt.Fprintf(w, "| %s |\n", strings.Join(cells, " | "))
}

func header(w io.Writer, cols ...string) {
	fmt.Fprintf(w, "| %s |\n|%s\n", strings.Join(cols, " | "), strings.Repeat("---|", len(cols)))
}
